sudo: required
before_install:
    - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.3.tar.gz
    - tar -zxvf libsodium-1.0.3.tar.gz
    - cd libsodium-1.0.3/ 
    - sudo ./configure
    - sudo make
    - sudo make install
    - cd..
    - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz
    - tar -zxvf zeromq-4.1.3.tar.gz
    - cd zeromq-4.1.3/
    - sudo ./configure
    - sudo make
    - sudo make install
    - cd..
    - sudo echo "/usr/local/lib" >> /etc/ld.so.conf
    - sudo ldconfig
language: node_js
node_js:
   - "0.12.7"
