before_install:
    - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.3.tar.gz
    - tar -zxvf libsodium-1.0.3.tar.gz
    - cd libsodium-1.0.3/ 
    - ./configure
    - make
    - make install
    - cd..
    - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz
    - tar -zxvf zeromq-4.1.3.tar.gz
    - cd zeromq-4.1.3/
    - ./configure
    - make
    - make install
    - cd..
    - echo "/usr/local/lib" >> /etc/ld.so.conf
    - ldconfig
language: node_js
node_js:
   - "0.12.7"
